name: 'Build dev container' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:

  list-folders:
    runs-on: ubuntu-latest
    steps:
      - uses: philips-labs/list-folder-action@v1
        with:
          directory: ./templates
          
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subfolder: ${{ fromJSON(needs.list-folders.outputs.folders) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ./templates/${{ matrix.subfolder }}
          imageName: ghcr.io/pnstack/codespace/${{ matrix.subfolder }}
          platform: linux/amd64,linux/arm64
          push: always