name: 'Build dev container' 

on: 
  pull_request:
  push:
    branches:
      - master

jobs:
  list-dir:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }} 
    steps:

      - name: List Dir
        id: list-dir
        uses: pnstack/actions/list-dir@main
        with: 
          dir: templates
  
  log:
    runs-on: ubuntu-latest
    needs: [list-dir] 
    steps:
      - name: Log
        run: echo ${{fromJson(needs.list-dir.outputs.dir)}}

  build:
    runs-on: ubuntu-latest
    needs: [list-dir] 
    strategy:
      matrix:
        dir: ${{fromJson(needs.list-dir.outputs.dir)}} 
    steps:
      - name: Checkout
        uses: actions/checkout@v4      

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ./templates/${{ matrix.dir }}
          imageName: ghcr.io/pnstack/codespace/${{ matrix.dir }}
          push: always