name: 'Build dev container' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Set matrix for build
        id: set-matrix
        run: |
          FOLDERS=$(ls -d templates/*/)
          FOLDERS=${FOLDERS%/} # remove trailing slashes
          FOLDERS=${FOLDERS//templates\//} # remove leading 'templates/'
          FOLDERS_JSON=$(echo "$FOLDERS" | jq -R -s -c 'split("\n")[:-1]')
          echo "FOLDERS_JSON: $FOLDERS_JSON"
          echo "::set-output name=matrix::${FOLDERS_JSON}"

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        subfolder: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        with:
          subFolder: ./templates/${{ matrix.subfolder }}
          imageName: ghcr.io/pnstack/codespace/${{ matrix.subfolder }}
          platform: linux/amd64,linux/arm64
          push: always