name: 'Test dev container' 
on: 
  pull_request:
  push:
    branches:
      - develop

jobs:
  directories:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.set-dirs.outputs.dir }} 
    steps:
      - uses: actions/checkout@v2
      - id: set-dirs 
        run: echo "name=dir::$(ls -d templates/*/ | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT
  
  loop:
    runs-on: ubuntu-latest
    needs: [directories] 
    strategy:
      matrix:
        dir: ${{fromJson(needs.directories.outputs.dir)}} 
    steps:
      - run: echo ${{matrix.dir}}

