name: 'Test dev container' 
on: 
  pull_request:
  push:
    branches:
      - develop

jobs:
  directories:
    runs-on: ubuntu-latest
    outputs:
      dir: ${{ steps.list-dir.outputs.dir }} 
    steps:
      - uses: actions/checkout@v2

      - name: List Dir
        id: list-dir
        uses: pnstack/actions/list-dir@main
  
  loop:
    runs-on: ubuntu-latest
    needs: [directories] 
    strategy:
      matrix:
        dir: ${{fromJson(needs.directories.outputs.dir)}} 
    steps:
      - run: echo ${{matrix.dir}}

